In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[71 61 34]
 [37 85 44]
 [44 55 58]]

Transposed Array:
[[71 37 44]
 [61 85 55]
 [34 44 58]]


In [3]:
'''2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.'''
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
print("1D Array:\n", array_1d)

# Step 2: Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\n2x5 Array:\n", array_2x5)

# Step 3: Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\n5x2 Array:\n", array_5x2)















1D Array:
 [0 1 2 3 4 5 6 7 8 9]

2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Step 2: Add a border of zeros to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:\n", array_6x6)




Original 4x4 Array:
 [[0.47046413 0.19247824 0.8602711  0.47511148]
 [0.19456389 0.49157651 0.1296904  0.96944263]
 [0.64050404 0.11660709 0.96472833 0.85347589]
 [0.21237455 0.9611521  0.58299886 0.91628569]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.47046413 0.19247824 0.8602711  0.47511148 0.        ]
 [0.         0.19456389 0.49157651 0.1296904  0.96944263 0.        ]
 [0.         0.64050404 0.11660709 0.96472833 0.85347589 0.        ]
 [0.         0.21237455 0.9611521  0.58299886 0.91628569 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create the array
array = np.arange(10, 61, 5)
print("Array from 10 to 60 with step of 5:\n", array)


Array from 10 to 60 with step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [11]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.



#import numpy as np

# Step 1: Create the array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

# Display results
print("Original Array:     ", string_array)
print("Uppercase:          ", uppercase_array)
print("Lowercase:          ", lowercase_array)
print("Title Case:         ", titlecase_array)
print("Capitalized:        ", capitalize_array)


Original Array:      ['python' 'numpy' 'pandas']
Uppercase:           ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:           ['python' 'numpy' 'pandas']
Title Case:          ['Python' 'Numpy' 'Pandas']
Capitalized:         ['Python' 'Numpy' 'Pandas']


In [12]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Step 1: Create the array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert a space between each character
spaced_words = np.char.join(' ', words_array)

# Display the result
print("Original Array: ", words_array)
print("Spaced Words:   ", spaced_words)


Original Array:  ['python' 'numpy' 'pandas']
Spaced Words:    ['p y t h o n' 'n u m p y' 'p a n d a s']


In [10]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Step 1: Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Step 2: Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nAddition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [8]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Step 1: Generate 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Step 2: Function to check for prime numbers
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Vectorize the function for NumPy
is_prime_vec = np.vectorize(is_prime)

# Step 4: Filter prime numbers
prime_numbers = random_integers[is_prime_vec(random_integers)]

# Display the results
print("Random Integers:\n", random_integers)
print("\nPrime Numbers:\n", prime_numbers)



Random Integers:
 [522 528 630 491 383 813 579 626 819 668 555 759 138  36 868  28 407 762
 432 176 394 975 767  69 278 222 385 350 693 636 345 154 957 254 541 194
 661 468 558 143 298 259 929 293 222 893 877 933 594 271 232 433  66 110
 106 784 345 412 860 455 337 533 105 697 808 530 307 555 307 969 938 499
 491 649 435 702 784 721 216 751 349 470 460 889 802 633 117  23 254 686
 110 832 779 431 916  55 735 279 281 904]

Prime Numbers:
 [491 383 541 661 929 293 877 271 433 337 307 307 499 491 751 349  23 431
 281]


In [7]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averag
import numpy as np

# Step 1: Generate random daily temperatures for 30 days (in °C)
daily_temps = np.random.uniform(low=15.0, high=40.0, size=30).round(1)
print("Daily Temperatures:\n", daily_temps)

# Step 2: Reshape into 4 full weeks + 2 extra days (assume weeks of 7 days)
weeks = daily_temps[:28].reshape(4, 7)  # First 4 full weeks

# Step 3: Calculate weekly averages
weekly_avg = weeks.mean(axis=1)
print("\nWeekly Average Temperatures:\n", weekly_avg)

# Optionally handle remaining days
if len(daily_temps) > 28:
    extra_days_avg = daily_temps[28:].mean()
    print("\nAverage of Remaining Days (Day 29-30):", round(extra_days_avg, 1))


Daily Temperatures:
 [34.8 30.2 20.2 27.9 21.6 21.3 19.3 23.  26.7 40.  39.2 33.2 35.3 20.8
 22.7 21.7 29.  31.4 27.9 23.6 33.1 19.6 32.3 30.3 30.8 25.1 19.8 25.6
 17.7 33. ]

Weekly Average Temperatures:
 [25.04285714 31.17142857 27.05714286 26.21428571]

Average of Remaining Days (Day 29-30): 25.4
