# Numpy Solution

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?
-  Ans:-
  - **Purpose**:
NumPy is designed to handle large arrays and matrices of numeric data efficiently. It provides powerful mathematical functions and operations essential for scientific and analytical tasks.

  - **Advantages**:

  Speed & Efficiency: Uses C under the hood.

  Multidimensional arrays: Supports tensors and matrices.

  Broadcasting & Vectorization: Replaces loops with fast array ops.

  Extensive math functions: FFT, linear algebra, statistics.

  Memory efficiency: Better than Python lists.




2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
--  >
	  -  np.mean():
   1)Arithmetic mean

   2)weight are not supported

   3)  Example:np.mean(arr)

   4)Use np.mean() for regular averaging.
   
  - np.average()

  1) Weighted average

   2)weights argument available

  3) Example np.average(arr, weights=w)

  4)Use np.average() when different elements contribute unequally.




3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
-- >
NumPy provides several methods to reverse arrays along different axes. Here are the common techniques with examples for both 1D and 2D arrays:

1. Reversing a 1D Array
For 1D arrays, you can use slicing with a step of -1:


    import numpy as np

    arr = np.array([1, 2, 3, 4, 5])
    reversed_arr = arr[::-1]  # Step -1 reverses the array

    print(reversed_arr)  # Output: [5 4 3 2 1]
   Alternatively, you can use np.flip():


    reversed_arr = np.flip(arr)
    print(reversed_arr)  # Output: [5 4 3 2 1]
2. Reversing a 2D Array
For 2D arrays, you can reverse along different axes:

Reverse rows (axis 0):

    arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

1. Reverse the order of rows:

   
   
    reversed_rows = arr_2d[::-1, :]
    or np.flip(arr_2d, axis=0)
    print(reversed_rows)
    
    Output:
    [[7 8 9]
     [4 5 6]
    [1 2 3]]
Reverse columns (axis 1):

# Reverse the order of columns
    reversed_cols = arr_2d[:, ::-1]  # or np.flip(arr_2d, axis=1)

    print(reversed_cols)
    Output:
    [[3 2 1]
    [6 5 4]
    [9 8 7]]
Reverse both rows and columns:
# Reverse both rows and columns
    reversed_both = arr_2d[::-1, ::-1]  # or np.flip(arr_2d)

    print(reversed_both)
    Output:
    [[9 8 7]
    [6 5 4]
    [3 2 1]]
   -  Using NumPy Functions
NumPy provides specific functions for these operations:

  -  np.flip(array) - Reverses all axes

  -  np.flip(array, axis=0) - Reverses along rows (first axis)

  - np.flip(array, axis=1) - Reverses along columns (second axis)

 - np.flipud(array) - Equivalent to flip(axis=0) (up-down)

    - np.fliplr(array) - Equivalent to flip(axis=1) (left-right)



4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
--
 - Determining Data Type in NumPy

       arr = np.array([1.0, 2.0])
       print(arr.dtype)  # float64

Importance of dtype:

Memory efficiency: Choose optimal size (int8, float32).

Speed: Smaller dtypes = faster operations.

Precision control: Crucial in scientific computing.



5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
-->
-  Definition:
  ndarray is the core data structure in NumPy for N-dimensional arrays.

- Key Features:

  -   Fixed-size, homogeneous data

  -   Fast vectorized ops

  -   Supports multi-dimensional slicing

  -   Methods for reshaping, aggregating, transforming

**vs Python Lists:**

  -  Faster and memory-efficient

  -  Supports broadcasting

  - Enables mathematical ops (not possible directly with lists)




6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
-- >Example:

    import numpy as np
    arr = np.arange(1e6)
    %timeit arr * 2  # Vectorized

  - vs Python list


    lst = list(range(int(1e6)))

    %timeit [x*2 for x in lst]  # Much slower

#Performance Benefits:

Vectorization removes Python loop overhead.

Operations use optimized C code internally.

Uses less memory with fixed data types.



7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.
--   >
Difference:

vstack() stacks along rows (adds new rows).

hstack() stacks along columns (extends horizontally).



    a = np.array([1, 2])
    b = np.array([3, 4])

    Vertical stack
    np.vstack((a, b))
    # → [[1, 2],
    #    [3, 4]]

    Horizontal stack
    np.hstack((a, b))
    # → [1, 2, 3, 4]



8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.
--
  fliplr(): Reverses columns

  flipud(): Reverses rows

  Useful in image processing, matrix transformations.


    arr = np.array([[1, 2], [3, 4]])

    np.fliplr(arr)  # Flip left to right
    # → [[2, 1], [4, 3]]

    np.flipud(arr)  # Flip upside down
    # → [[3, 4], [1, 2]]


 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

 -  np.array_split() is used to divide a NumPy array into sub-arrays, even when the number of elements cannot be split equally.


.

If not, array_split() distributes the remainder across the first few sub-arrays, ensuring no error is thrown (unlike np.split() which fails on uneven division).

   Example:

    import numpy as np

    arr = np.arange(10)
    result = np.array_split(arr, 3)

    for i, r in enumerate(result):
    print(f"Part {i+1}: {r}")


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?
- Vectorization
  - Definition:
Vectorization is the process of replacing explicit loops with array expressions to perform operations on entire arrays simultaneously.

Example:


    import numpy as np
    arr = np.array([1, 2, 3, 4])
    squared = arr ** 2  # Vectorized
    # Output: [1 4 9 16]

Without vectorization (slower):

    squared = [x**2 for x in [1, 2, 3, 4]]
  - Broadcasting
-   Definition:
Broadcasting automatically expands smaller arrays so they can match the shape of larger arrays in arithmetic operations without actual data replication.

Rules:

Dimensions must match or be 1.

NumPy virtually expands the smaller array to perform operations.

Example:


    a = np.array([[1], [2], [3]])  # shape (3,1)
    b = np.array([10, 20, 30])     # shape (3,)
    result = a + b
    Output:
    [[11 21 31]
    [12 22 32]
    [13 23 33]]
a expands to shape (3,3) to match b automatically.



















In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[71 61 34]
 [37 85 44]
 [44 55 58]]

Transposed Array:
[[71 37 44]
 [61 85 55]
 [34 44 58]]


In [3]:
'''2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.'''
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
print("1D Array:\n", array_1d)

# Step 2: Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\n2x5 Array:\n", array_2x5)

# Step 3: Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\n5x2 Array:\n", array_5x2)















1D Array:
 [0 1 2 3 4 5 6 7 8 9]

2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Step 2: Add a border of zeros to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:\n", array_6x6)




Original 4x4 Array:
 [[0.47046413 0.19247824 0.8602711  0.47511148]
 [0.19456389 0.49157651 0.1296904  0.96944263]
 [0.64050404 0.11660709 0.96472833 0.85347589]
 [0.21237455 0.9611521  0.58299886 0.91628569]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.47046413 0.19247824 0.8602711  0.47511148 0.        ]
 [0.         0.19456389 0.49157651 0.1296904  0.96944263 0.        ]
 [0.         0.64050404 0.11660709 0.96472833 0.85347589 0.        ]
 [0.         0.21237455 0.9611521  0.58299886 0.91628569 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create the array
array = np.arange(10, 61, 5)
print("Array from 10 to 60 with step of 5:\n", array)


Array from 10 to 60 with step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [11]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.



#import numpy as np

# Step 1: Create the array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

# Display results
print("Original Array:     ", string_array)
print("Uppercase:          ", uppercase_array)
print("Lowercase:          ", lowercase_array)
print("Title Case:         ", titlecase_array)
print("Capitalized:        ", capitalize_array)


Original Array:      ['python' 'numpy' 'pandas']
Uppercase:           ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:           ['python' 'numpy' 'pandas']
Title Case:          ['Python' 'Numpy' 'Pandas']
Capitalized:         ['Python' 'Numpy' 'Pandas']


In [12]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Step 1: Create the array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert a space between each character
spaced_words = np.char.join(' ', words_array)

# Display the result
print("Original Array: ", words_array)
print("Spaced Words:   ", spaced_words)


Original Array:  ['python' 'numpy' 'pandas']
Spaced Words:    ['p y t h o n' 'n u m p y' 'p a n d a s']


In [10]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Step 1: Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Step 2: Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nAddition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [8]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Step 1: Generate 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Step 2: Function to check for prime numbers
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Vectorize the function for NumPy
is_prime_vec = np.vectorize(is_prime)

# Step 4: Filter prime numbers
prime_numbers = random_integers[is_prime_vec(random_integers)]

# Display the results
print("Random Integers:\n", random_integers)
print("\nPrime Numbers:\n", prime_numbers)



Random Integers:
 [522 528 630 491 383 813 579 626 819 668 555 759 138  36 868  28 407 762
 432 176 394 975 767  69 278 222 385 350 693 636 345 154 957 254 541 194
 661 468 558 143 298 259 929 293 222 893 877 933 594 271 232 433  66 110
 106 784 345 412 860 455 337 533 105 697 808 530 307 555 307 969 938 499
 491 649 435 702 784 721 216 751 349 470 460 889 802 633 117  23 254 686
 110 832 779 431 916  55 735 279 281 904]

Prime Numbers:
 [491 383 541 661 929 293 877 271 433 337 307 307 499 491 751 349  23 431
 281]


In [7]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averag
import numpy as np

# Step 1: Generate random daily temperatures for 30 days (in °C)
daily_temps = np.random.uniform(low=15.0, high=40.0, size=30).round(1)
print("Daily Temperatures:\n", daily_temps)

# Step 2: Reshape into 4 full weeks + 2 extra days (assume weeks of 7 days)
weeks = daily_temps[:28].reshape(4, 7)  # First 4 full weeks

# Step 3: Calculate weekly averages
weekly_avg = weeks.mean(axis=1)
print("\nWeekly Average Temperatures:\n", weekly_avg)

# Optionally handle remaining days
if len(daily_temps) > 28:
    extra_days_avg = daily_temps[28:].mean()
    print("\nAverage of Remaining Days (Day 29-30):", round(extra_days_avg, 1))


Daily Temperatures:
 [34.8 30.2 20.2 27.9 21.6 21.3 19.3 23.  26.7 40.  39.2 33.2 35.3 20.8
 22.7 21.7 29.  31.4 27.9 23.6 33.1 19.6 32.3 30.3 30.8 25.1 19.8 25.6
 17.7 33. ]

Weekly Average Temperatures:
 [25.04285714 31.17142857 27.05714286 26.21428571]

Average of Remaining Days (Day 29-30): 25.4
